name: Unit Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run Tests
        run: |
          npm run test